import assert from "node:assert/strict";
import test from "node:test";
import { Client, InMemoryTransport } from "@modelcontextprotocol/client";
import type { Reminder, Task } from "@pulse/api-client";
import { createPulseMcpServer, type PulseMcpApi } from "../src/server.js";

const reminder=(overrides:Partial<Reminder>={}):Reminder=>({id:"rem-1",taskId:"task-1",userId:"user-1",remindAt:"2026-08-23T02:30:00.000Z",channel:"hermes_telegram",status:"pending",createdAt:"2026-08-21T00:00:00.000Z",updatedAt:"2026-08-21T00:00:00.000Z",deletedAt:null,...overrides});
function task(overrides:Partial<Task>={}):Task{return{id:"task-1",userId:"user-1",title:"Test task",description:null,status:"open",priority:"none",startAt:null,endAt:null,due:{date:null,at:null},recurrenceRule:null,completedAt:null,deletedAt:null,projectId:null,parentTaskId:null,sortOrder:0,revision:1,tags:[],reminders:[],createdAt:"2026-08-21T00:00:00.000Z",updatedAt:"2026-08-21T00:00:00.000Z",...overrides};}
function makeApi(){
  const calls:Array<{method:string;args:unknown[]}>=[];
  const api:PulseMcpApi={
    async getToday(include=false){calls.push({method:"getToday",args:[include]});return[task()];},async getInbox(include=false){calls.push({method:"getInbox",args:[include]});return[task({id:"inbox-1"})];},
    async searchTasks(q){calls.push({method:"searchTasks",args:[q]});return[task({title:q})];},
    async createTask(input){calls.push({method:"createTask",args:[input]});return task({title:input.title,priority:input.priority??"none",startAt:input.startAt??null,endAt:input.endAt??null,due:{date:input.dueDate??null,at:input.dueAt??null}});},
    async updateTask(id,input){calls.push({method:"updateTask",args:[id,input]});return task({id,title:input.title??"Test task",priority:input.priority??"none",startAt:input.startAt??null,endAt:input.endAt??null});},
    async completeTask(id){calls.push({method:"completeTask",args:[id]});return task({id,status:"completed"});},
    async rescheduleTask(id,input){calls.push({method:"rescheduleTask",args:[id,input]});return task({id,startAt:input.startAt??null,endAt:input.endAt??null,due:{date:input.dueDate??null,at:input.dueAt??null},recurrenceRule:input.recurrenceRule??null});},
    async getTask(id){calls.push({method:"getTask",args:[id]});return task({id});},async getUpcoming(include=false){calls.push({method:"getUpcoming",args:[include]});return[task({id:"upcoming-1"})];},async getOverdue(){calls.push({method:"getOverdue",args:[]});return[task({id:"overdue-1"})];},
    async reopenTask(id){calls.push({method:"reopenTask",args:[id]});return task({id});},async cancelTask(id){calls.push({method:"cancelTask",args:[id]});return task({id,status:"cancelled"});},
    async moveTask(id,input){calls.push({method:"moveTask",args:[id,input]});return task({id,projectId:input.projectId});},async bulkComplete(input){calls.push({method:"bulkComplete",args:[input]});return input.ids.map(id=>task({id,status:"completed"}));},
    async bulkReschedule(input){calls.push({method:"bulkReschedule",args:[input]});return input.ids.map(id=>task({id,startAt:input.startAt??null,endAt:input.endAt??null,due:{date:input.dueDate??null,at:input.dueAt??null}}));},async bulkMove(input){calls.push({method:"bulkMove",args:[input]});return input.ids.map(id=>task({id,projectId:input.projectId}));},
    async listProjects(){calls.push({method:"listProjects",args:[]});return[];},async listTags(){calls.push({method:"listTags",args:[]});return[];},async setTaskLabels(id,tagIds){calls.push({method:"setTaskLabels",args:[id,tagIds]});return task({id});},
    async listReminders(id){calls.push({method:"listReminders",args:[id]});return[reminder({taskId:id})];},async createReminder(id,input){calls.push({method:"createReminder",args:[id,input]});return reminder({taskId:id,remindAt:input.remindAt,channel:input.channel??"hermes_telegram"});},
    async updateReminder(id,input){calls.push({method:"updateReminder",args:[id,input]});return reminder({id,remindAt:input.remindAt??"2026-08-23T02:30:00.000Z",channel:input.channel??"hermes_telegram",status:input.status??"pending"});},async deleteReminder(id){calls.push({method:"deleteReminder",args:[id]});},
    async createComment(id,input){calls.push({method:"createComment",args:[id,input]});return{id:"c",taskId:id,userId:"user-1",body:input.body,createdAt:"2026-08-21T00:00:00Z",updatedAt:"2026-08-21T00:00:00Z",deletedAt:null};},async getTaskHistory(id){calls.push({method:"getTaskHistory",args:[id]});return[];},
  };return{api,calls};
}
async function connect(api:PulseMcpApi){const server=createPulseMcpServer(api);const client=new Client({name:"pulse-test",version:"0.1.0"});const[c,s]=InMemoryTransport.createLinkedPair();await server.connect(s);await client.connect(c);return{client,server};}

test("lists the expanded structured Pulse MCP surface",async()=>{const{api}=makeApi();const{client,server}=await connect(api);try{const names=(await client.listTools()).tools.map(t=>t.name).sort();for(const name of ["create_task","update_task","reschedule_task","set_task_labels","get_task_reminders","add_task_reminder","update_task_reminder","delete_task_reminder","move_task","get_today","get_upcoming"])assert.ok(names.includes(name),name);assert.equal(names.length,25);}finally{await client.close();await server.close();}});
test("view tools can include completed tasks",async()=>{const{api,calls}=makeApi();const{client,server}=await connect(api);try{await client.callTool({name:"get_today",arguments:{includeCompleted:true}});await client.callTool({name:"get_inbox",arguments:{includeCompleted:true}});await client.callTool({name:"get_upcoming",arguments:{includeCompleted:true}});assert.deepEqual(calls.map(c=>c.args),[[true],[true],[true]]);}finally{await client.close();await server.close();}});
test("task mutations expose schedule window, deadline, priority, project, labels and recurrence",async()=>{const{api,calls}=makeApi();const{client,server}=await connect(api);try{
  await client.callTool({name:"create_task",arguments:{title:"Build MCP",startAt:"2026-08-23T01:00:00.000Z",endAt:"2026-08-23T02:00:00.000Z",dueAt:"2026-08-23T04:00:00.000Z",priority:"urgent",projectId:"project-1",tagIds:["label-1"],reminders:[{remindAt:"2026-08-23T00:30:00.000Z"}],recurrenceRule:"FREQ=WEEKLY"}});
  await client.callTool({name:"reschedule_task",arguments:{id:"task-1",startAt:"2026-08-24T01:00:00.000Z",endAt:"2026-08-24T02:00:00.000Z",dueDate:"2026-08-24"}});
  await client.callTool({name:"move_task",arguments:{id:"task-1",projectId:null}});await client.callTool({name:"set_task_labels",arguments:{id:"task-1",tagIds:["label-2"]}});
  assert.equal((calls[0]!.args[0] as {priority:string}).priority,"urgent");assert.deepEqual(calls[2],{method:"moveTask",args:["task-1",{projectId:null}]});assert.deepEqual(calls[3],{method:"setTaskLabels",args:["task-1",["label-2"]]});
}finally{await client.close();await server.close();}});
test("reminder CRUD stays structured and defaults channel downstream",async()=>{const{api,calls}=makeApi();const{client,server}=await connect(api);try{await client.callTool({name:"get_task_reminders",arguments:{id:"task-1"}});await client.callTool({name:"add_task_reminder",arguments:{id:"task-1",remindAt:"2026-08-23T02:30:00.000Z"}});await client.callTool({name:"update_task_reminder",arguments:{reminderId:"rem-1",status:"sent"}});await client.callTool({name:"delete_task_reminder",arguments:{reminderId:"rem-1"}});assert.deepEqual(calls.map(c=>c.method),["listReminders","createReminder","updateReminder","deleteReminder"]);}finally{await client.close();await server.close();}});
test("invalid natural-language date is rejected before API call",async()=>{const{api,calls}=makeApi();const{client,server}=await connect(api);try{const r=await client.callTool({name:"create_task",arguments:{title:"Bad",dueDate:"tomorrow"}});assert.equal(r.isError,true);assert.equal(calls.length,0);}finally{await client.close();await server.close();}});
