import { getRepository } from "../repositories/registry.js";
import type { Project, Section, UserId } from "@pulse/domain";
import type { CreateProjectInput, CreateSectionInput, UpdateProjectInput, UpdateSectionInput } from "@pulse/api-client";
export const listProjects=(u:UserId):Promise<Project[]>=>getRepository().projects.list(u);
export const createProject=(u:UserId,i:CreateProjectInput):Promise<Project>=>getRepository().projects.create(u,i);
export const getProject=(u:UserId,id:string):Promise<Project>=>getRepository().projects.get(u,id);
export const updateProject=(u:UserId,id:string,i:UpdateProjectInput):Promise<Project>=>getRepository().projects.update(u,id,i);
export const archiveProject=(u:UserId,id:string):Promise<Project>=>getRepository().projects.archive(u,id);
export const deleteProject=(u:UserId,id:string):Promise<void>=>getRepository().projects.delete(u,id);
export const listSections=(u:UserId,p:string):Promise<Section[]>=>getRepository().sections.list(u,p);
export const createSection=(u:UserId,i:CreateSectionInput):Promise<Section>=>getRepository().sections.create(u,i);
export const updateSection=(u:UserId,p:string,id:string,i:UpdateSectionInput):Promise<Section>=>getRepository().sections.update(u,p,id,i);
export const deleteSection=(u:UserId,p:string,id:string):Promise<void>=>getRepository().sections.delete(u,p,id);
