import { ArrowLeft, CheckCircle2 } from "lucide-react-native";
import { router } from "expo-router";
import { useEffect, useState } from "react";
import { Alert, Platform, Pressable, ScrollView, StyleSheet, Switch, TextInput, View } from "react-native";
import Constants from "expo-constants";
import * as Device from "expo-device";
import * as Notifications from "expo-notifications";
import type { NotificationPreferences, UpdateNotificationPreferences } from "@pulse/api-client";
import { AppText, PrimaryButton, Screen } from "@/components/ui";
import { useAuth } from "@/providers/auth-provider";
import { useAppTheme } from "@/providers/theme-provider";

export default function NotificationSettingsScreen() {
  const { api } = useAuth(); const { palette } = useAppTheme(); const [settings, setSettings] = useState<NotificationPreferences | null>(null); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false);
  useEffect(() => { api.getNotificationPreferences().then(setSettings).catch(() => Alert.alert("Could not load reminders", "Reconnect to Pulse and try again.")); }, [api]);
  const patch = <K extends keyof UpdateNotificationPreferences>(key: K, value: UpdateNotificationPreferences[K]) => setSettings((current) => current ? { ...current, [key]: value } : current);
  const minuteList = (value: string) => [...new Set(value.split(",").map((item) => Number(item.trim())).filter((item) => Number.isInteger(item) && item >= 0 && item <= 10080))].slice(0, 8);
  const row = (label: string, detail: string, key: keyof Pick<UpdateNotificationPreferences, "enabled" | "hermesEnabled" | "fallbackEnabled" | "emailEnabled" | "pushEnabled" | "quietHoursEnabled" | "includeDescription" | "includeProject" | "includeDue" | "includePriority">) => <View style={[styles.row, { borderBottomColor: palette.border }]}><View style={styles.copy}><AppText style={styles.label}>{label}</AppText><AppText muted style={styles.detail}>{detail}</AppText></View><Switch value={Boolean(settings?.[key])} onValueChange={(value) => patch(key, value)} trackColor={{ true: palette.accent }} /></View>;
  if (!settings) return <Screen><View style={styles.header}><Pressable onPress={() => router.back()}><ArrowLeft size={22} color={palette.text} /></Pressable><AppText style={styles.heading}>Reminders</AppText></View><AppText muted style={styles.loading}>Loading…</AppText></Screen>;
  const registerPhone = async () => {
    if (!Device.isDevice) throw new Error("Push notifications require a physical phone.");
    if (Platform.OS === "android") await Notifications.setNotificationChannelAsync("reminders", { name: "Task reminders", importance: Notifications.AndroidImportance.HIGH });
    const current = await Notifications.getPermissionsAsync();
    const permission = current.status === "granted" ? current : await Notifications.requestPermissionsAsync();
    if (permission.status !== "granted") throw new Error("Notification permission was not granted.");
    const projectId = Constants.expoConfig?.extra?.eas?.projectId ?? Constants.easConfig?.projectId;
    if (!projectId) throw new Error("This Pulse build does not have an Expo project ID yet.");
    const token = (await Notifications.getExpoPushTokenAsync({ projectId })).data;
    await api.registerPushDevice(token, Platform.OS === "ios" ? "ios" : "android");
  };
  const save = async () => { setSaving(true); try { if (settings.pushEnabled) await registerPhone(); setSettings(await api.updateNotificationPreferences(settings)); setSaved(true); } catch (error) { Alert.alert("Could not save", error instanceof Error ? error.message : "Reconnect to Pulse and try again."); } finally { setSaving(false); } };
  return <Screen><View style={styles.header}><Pressable onPress={() => router.back()}><ArrowLeft size={22} color={palette.text} /></Pressable><AppText style={styles.heading}>Reminders</AppText></View><ScrollView contentContainerStyle={styles.content}>
    {row("Enable reminders", "Deliver reminders when they become due.", "enabled")}{row("Hermes primary", settings.hermesConfigured ? "Configured on this server." : "Server setup is still required.", "hermesEnabled")}{row("Telegram fallback", settings.fallbackConfigured ? "Independent fallback bot configured." : "A fallback bot token is still required.", "fallbackEnabled")}{row("Email", settings.emailConfigured ? "Send an additional email reminder." : "SMTP server setup is required.", "emailEnabled")}{settings.emailEnabled ? <TextInput value={settings.emailAddress ?? ""} onChangeText={(value) => patch("emailAddress", value || null)} autoCapitalize="none" keyboardType="email-address" placeholder="Use account email" placeholderTextColor={palette.textMuted} style={[styles.input, { borderColor: palette.border, color: palette.text }]} /> : null}{row("Phone notifications", `${settings.registeredPushDevices} registered phone${settings.registeredPushDevices === 1 ? "" : "s"}. Saving will register this phone.`, "pushEnabled")}
    <AppText muted style={styles.section}>Delivery</AppText><AppText style={styles.label}>Fallback timeout in seconds</AppText><TextInput keyboardType="number-pad" value={String(settings.fallbackAfterSeconds)} onChangeText={(value) => patch("fallbackAfterSeconds", Math.max(3, Math.min(120, Number(value) || 3)))} style={[styles.input, { borderColor: palette.border, color: palette.text }]} />
    <View style={styles.chips}>{(["detailed", "compact"] as const).map((value) => <Pressable key={value} onPress={() => patch("deliveryStyle", value)} style={[styles.chip, { borderColor: settings.deliveryStyle === value ? palette.accent : palette.border, backgroundColor: settings.deliveryStyle === value ? palette.accentSoft : palette.surface }]}><AppText>{value[0].toUpperCase() + value.slice(1)}</AppText></Pressable>)}</View>
    {row("Quiet hours", "Delay, silence, or normally deliver overnight.", "quietHoursEnabled")}{settings.quietHoursEnabled ? <><View style={styles.timeRow}><TextInput value={settings.quietStart} onChangeText={(v) => patch("quietStart", v)} placeholder="22:00" style={[styles.input, styles.time, { borderColor: palette.border, color: palette.text }]} /><TextInput value={settings.quietEnd} onChangeText={(v) => patch("quietEnd", v)} placeholder="07:00" style={[styles.input, styles.time, { borderColor: palette.border, color: palette.text }]} /></View><View style={styles.chips}>{(["delay", "silent", "send"] as const).map((value) => <Pressable key={value} onPress={() => patch("quietMode", value)} style={[styles.chip, { borderColor: settings.quietMode === value ? palette.accent : palette.border, backgroundColor: settings.quietMode === value ? palette.accentSoft : palette.surface }]}><AppText>{value === "send" ? "Normal" : value[0].toUpperCase() + value.slice(1)}</AppText></Pressable>)}</View></> : null}
    <AppText muted style={styles.section}>Detailed message</AppText>{row("Description", "Include the task description.", "includeDescription")}{row("Project", "Include the project name.", "includeProject")}{row("Due date", "Include the deadline.", "includeDue")}{row("Priority", "Include priority when set.", "includePriority")}
    <AppText muted style={styles.section}>Presets and destination</AppText><AppText style={styles.label}>Default lead-time presets (minutes)</AppText><TextInput value={settings.defaultLeadMinutes.join(", ")} onChangeText={(value) => patch("defaultLeadMinutes", minuteList(value))} style={[styles.input, { borderColor: palette.border, color: palette.text }]} /><AppText style={[styles.label, { marginTop: 14 }]}>Snooze presets (minutes)</AppText><TextInput value={settings.snoozeMinutes.join(", ")} onChangeText={(value) => patch("snoozeMinutes", minuteList(value))} style={[styles.input, { borderColor: palette.border, color: palette.text }]} /><AppText style={[styles.label, { marginTop: 14 }]}>Telegram chat override</AppText><TextInput value={settings.telegramChatId ?? ""} onChangeText={(value) => patch("telegramChatId", value || null)} placeholder="Use server default" placeholderTextColor={palette.textMuted} style={[styles.input, { borderColor: palette.border, color: palette.text }]} /><AppText style={[styles.label, { marginTop: 14 }]}>Telegram topic override</AppText><TextInput value={settings.telegramThreadId ?? ""} onChangeText={(value) => patch("telegramThreadId", value || null)} placeholder="Use server default" placeholderTextColor={palette.textMuted} style={[styles.input, { borderColor: palette.border, color: palette.text }]} />
    <PrimaryButton loading={saving} onPress={save} style={styles.save}>Save reminder settings</PrimaryButton>{saved ? <View style={styles.saved}><CheckCircle2 size={17} color="#18864b" /><AppText style={{ color: "#18864b" }}>Saved</AppText></View> : null}
  </ScrollView></Screen>;
}

const styles = StyleSheet.create({ header: { minHeight: 88, paddingHorizontal: 20, paddingTop: 20, flexDirection: "row", alignItems: "center", gap: 14 }, heading: { fontSize: 28, fontWeight: "800" }, loading: { padding: 20 }, content: { paddingHorizontal: 20, paddingBottom: 80, maxWidth: 720, width: "100%", alignSelf: "center" }, row: { minHeight: 66, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", alignItems: "center", gap: 12 }, copy: { flex: 1, paddingVertical: 10 }, label: { fontSize: 14.5, fontWeight: "700" }, detail: { fontSize: 11.5, lineHeight: 16, marginTop: 2 }, section: { fontSize: 12, fontWeight: "700", textTransform: "uppercase", letterSpacing: 0.7, marginTop: 24, marginBottom: 8 }, input: { height: 44, borderWidth: StyleSheet.hairlineWidth, borderRadius: 10, paddingHorizontal: 12, marginTop: 8 }, chips: { flexDirection: "row", gap: 8, marginVertical: 14 }, chip: { minHeight: 38, borderWidth: StyleSheet.hairlineWidth, borderRadius: 10, paddingHorizontal: 14, alignItems: "center", justifyContent: "center" }, timeRow: { flexDirection: "row", gap: 10 }, time: { flex: 1 }, save: { marginTop: 22 }, saved: { marginTop: 10, flexDirection: "row", justifyContent: "center", alignItems: "center", gap: 6 } });
