import { prisma } from "@pulse/db";
import { dayBoundsInTimezone, formatDateInTimezone, normalizeTaskSchedule, parseRecurrenceRule } from "@pulse/domain";
import { Errors } from "../lib/errors.js";
import { serializeComment, serializeOperation, serializeProject, serializeReminder, serializeTag, serializeTask, serializeTaskEvent } from "../services/task-serializer.js";
import type { PulseRepository, TaskSnapshot } from "./types.js";

const taskInclude={tags:{include:{tag:true}},reminders:{where:{deletedAt:null},orderBy:{remindAt:"asc" as const}}} as const;
function found<T>(value:T|null|undefined,resource:string):asserts value is T{if(!value)throw Errors.NotFound(resource);}
function priority(value:string){return value.toUpperCase() as "NONE"|"LOW"|"MEDIUM"|"HIGH"|"URGENT";}
function status(value:string){return value.toUpperCase() as "OPEN"|"COMPLETED"|"CANCELLED";}
function validateRecurrence(value:string|null|undefined){if(value)parseRecurrenceRule(value);}
async function ensureProject(userId:string,id:string){const p=await prisma.project.findFirst({where:{id,userId,deletedAt:null}});found(p,"Project");return p;}
async function ensureTask(userId:string,id:string,includeDeleted=false){const t=await prisma.task.findFirst({where:{id,userId,deletedAt:includeDeleted?undefined:null}});found(t,"Task");return t;}
async function ensureTags(userId:string,ids:string[]){const unique=[...new Set(ids)];if(!unique.length)return;const count=await prisma.tag.count({where:{id:{in:unique},userId,deletedAt:null}});if(count!==unique.length)throw Errors.Validation("One or more labels do not belong to the user.");}
async function ensureTaskIds(userId:string,ids:string[]){const unique=[...new Set(ids)];const count=await prisma.task.count({where:{id:{in:unique},userId,deletedAt:null}});if(count!==unique.length)throw Errors.NotFound("Task");}
async function validateRelations(userId:string,input:{projectId?:string|null;parentTaskId?:string|null;tagIds?:string[];addTagIds?:string[];removeTagIds?:string[]}){if(input.projectId)await ensureProject(userId,input.projectId);if(input.parentTaskId)await ensureTask(userId,input.parentTaskId);await ensureTags(userId,[...(input.tagIds??[]),...(input.addTagIds??[]),...(input.removeTagIds??[])]);}

async function snapshot(userId:string,id:string):Promise<TaskSnapshot>{
  const t=await prisma.task.findFirst({where:{id,userId},include:{tags:{select:{tagId:true}},reminders:{where:{deletedAt:null},orderBy:{remindAt:"asc"}}}});found(t,"Task");
  return{taskId:id,before:{title:t.title,description:t.description,location:t.location,status:t.status,priority:t.priority,startAt:t.startAt?.toISOString()??null,endAt:t.endAt?.toISOString()??null,dueDate:t.dueDate?.toISOString()??null,dueAt:t.dueAt?.toISOString()??null,recurrenceRule:t.recurrenceRule,projectId:t.projectId,parentTaskId:t.parentTaskId,tagIds:t.tags.map((x)=>x.tagId),reminders:t.reminders.map((r)=>({remindAt:r.remindAt.toISOString(),channel:r.channel,status:r.status})),completedAt:t.completedAt?.toISOString()??null,deletedAt:t.deletedAt?.toISOString()??null,sortOrder:t.sortOrder,revision:t.revision}};
}
async function restoreSnapshot(userId:string,s:TaskSnapshot):Promise<void>{
  await ensureTask(userId,s.taskId,true);const b=s.before;const reminderValues=(b.reminders as Array<{remindAt:string;channel?:string;status?:string}>)??[];
  await prisma.$transaction(async(tx)=>{
    await tx.task.update({where:{id:s.taskId},data:{title:b.title as string,description:(b.description as string|null)??null,location:(b.location as string|null)??null,status:status(b.status as string),priority:priority(b.priority as string),startAt:b.startAt?new Date(b.startAt as string):null,endAt:b.endAt?new Date(b.endAt as string):null,dueDate:b.dueDate?new Date(b.dueDate as string):null,dueAt:b.dueAt?new Date(b.dueAt as string):null,recurrenceRule:(b.recurrenceRule as string|null)??null,projectId:(b.projectId as string|null)??null,parentTaskId:(b.parentTaskId as string|null)??null,completedAt:b.completedAt?new Date(b.completedAt as string):null,deletedAt:b.deletedAt?new Date(b.deletedAt as string):null,sortOrder:Number(b.sortOrder??0),revision:{increment:1}}});
    await tx.taskTag.deleteMany({where:{taskId:s.taskId}});const tagIds=(b.tagIds as string[])??[];if(tagIds.length)await tx.taskTag.createMany({data:tagIds.map((tagId)=>({taskId:s.taskId,tagId})),skipDuplicates:true});
    await tx.reminder.updateMany({where:{taskId:s.taskId,userId,deletedAt:null},data:{deletedAt:new Date()}});if(reminderValues.length)await tx.reminder.createMany({data:reminderValues.map((r)=>({userId,taskId:s.taskId,remindAt:new Date(r.remindAt),channel:r.channel??"hermes_telegram",status:r.status??"pending"}))});
  });
}
async function replaceReminders(tx:Parameters<Parameters<typeof prisma.$transaction>[0]>[0],userId:string,taskId:string,values:Array<{remindAt:string;channel?:string}>){await tx.reminder.updateMany({where:{userId,taskId,deletedAt:null},data:{deletedAt:new Date()}});if(values.length)await tx.reminder.createMany({data:values.map((r)=>({userId,taskId,remindAt:new Date(r.remindAt),channel:r.channel??"hermes_telegram",status:"pending"}))});}
function mergedSchedule(task:{startAt:Date|null;endAt:Date|null;dueDate:Date|null;dueAt:Date|null},input:{startAt?:string|null;endAt?:string|null;dueDate?:string|null;dueAt?:string|null}){
  const startAt=input.startAt===undefined?(task.startAt?.toISOString()??null):input.startAt;
  const endAt=input.endAt===undefined?(task.endAt?.toISOString()??null):input.endAt;
  let dueDate=input.dueDate===undefined?(task.dueDate?.toISOString().slice(0,10)??null):input.dueDate;
  let dueAt=input.dueAt===undefined?(task.dueAt?.toISOString()??null):input.dueAt;
  if(input.dueDate!==undefined&&input.dueAt===undefined)dueAt=null;
  if(input.dueAt!==undefined&&input.dueDate===undefined)dueDate=null;
  return normalizeTaskSchedule({startAt,endAt,dueDate,dueAt});
}

export const prismaRepository:PulseRepository={
  healthCheck:async()=>{try{await prisma.$queryRaw`SELECT 1`;return{database:"connected"};}catch{return{database:"disconnected"};}},
  tasks:{
    list:async(userId,filters={})=>(await prisma.task.findMany({where:{userId,deletedAt:null,status:filters.status?status(filters.status):undefined,projectId:filters.projectId??undefined},include:taskInclude,orderBy:[{sortOrder:"asc"},{createdAt:"desc"}]})).map(serializeTask),
    create:async(userId,input)=>{validateRecurrence(input.recurrenceRule);await validateRelations(userId,input);const s=normalizeTaskSchedule(input);const created=await prisma.$transaction(async(tx)=>{const task=await tx.task.create({data:{userId,title:input.title,description:input.description??null,location:input.location??null,priority:priority(input.priority??"none"),startAt:s.startAt?new Date(s.startAt):null,endAt:s.endAt?new Date(s.endAt):null,dueDate:s.due.date?new Date(`${s.due.date}T00:00:00Z`):null,dueAt:s.due.at?new Date(s.due.at):null,recurrenceRule:input.recurrenceRule??null,projectId:input.projectId??null,parentTaskId:input.parentTaskId??null,sortOrder:input.sortOrder??0}});if(input.tagIds?.length)await tx.taskTag.createMany({data:input.tagIds.map((tagId)=>({taskId:task.id,tagId}))});if(input.reminders?.length)await tx.reminder.createMany({data:input.reminders.map((r)=>({userId,taskId:task.id,remindAt:new Date(r.remindAt),channel:r.channel??"hermes_telegram",status:"pending"}))});return task;});const t=await prisma.task.findUnique({where:{id:created.id},include:taskInclude});found(t,"Task");return serializeTask(t);},
    get:async(userId,id)=>{const t=await prisma.task.findFirst({where:{id,userId,deletedAt:null},include:taskInclude});found(t,"Task");return serializeTask(t);},
    update:async(userId,id,input)=>{const current=await ensureTask(userId,id);validateRecurrence(input.recurrenceRule);await validateRelations(userId,input);const s=mergedSchedule(current,input);const data:Record<string,unknown>={revision:{increment:1}};if(input.title!==undefined)data.title=input.title;if(input.description!==undefined)data.description=input.description;if(input.location!==undefined)data.location=input.location;if(input.priority!==undefined)data.priority=priority(input.priority);if(input.startAt!==undefined)data.startAt=s.startAt?new Date(s.startAt):null;if(input.endAt!==undefined)data.endAt=s.endAt?new Date(s.endAt):null;if(input.dueDate!==undefined){data.dueDate=s.due.date?new Date(`${s.due.date}T00:00:00Z`):null;if(input.dueAt===undefined)data.dueAt=null;}if(input.dueAt!==undefined){data.dueAt=s.due.at?new Date(s.due.at):null;if(input.dueDate===undefined)data.dueDate=null;}if(input.recurrenceRule!==undefined)data.recurrenceRule=input.recurrenceRule;if(input.projectId!==undefined)data.projectId=input.projectId;if(input.parentTaskId!==undefined)data.parentTaskId=input.parentTaskId;if(input.sortOrder!==undefined)data.sortOrder=input.sortOrder;await prisma.$transaction(async(tx)=>{if(input.tagIds!==undefined){await tx.taskTag.deleteMany({where:{taskId:id}});if(input.tagIds.length)await tx.taskTag.createMany({data:input.tagIds.map((tagId)=>({taskId:id,tagId}))});}if(input.reminders!==undefined)await replaceReminders(tx,userId,id,input.reminders);await tx.task.update({where:{id},data});});const t=await prisma.task.findUnique({where:{id},include:taskInclude});found(t,"Task");return serializeTask(t);},
    delete:async(userId,id)=>{await ensureTask(userId,id);await prisma.task.update({where:{id},data:{deletedAt:new Date(),revision:{increment:1}}});},
    complete:async(userId,id,completedAt)=>{await ensureTask(userId,id);return serializeTask(await prisma.task.update({where:{id},data:{status:"COMPLETED",completedAt,revision:{increment:1}},include:taskInclude}));},
    reopen:async(userId,id)=>{await ensureTask(userId,id);return serializeTask(await prisma.task.update({where:{id},data:{status:"OPEN",completedAt:null,revision:{increment:1}},include:taskInclude}));},
    cancel:async(userId,id)=>{await ensureTask(userId,id);return serializeTask(await prisma.task.update({where:{id},data:{status:"CANCELLED",completedAt:null,revision:{increment:1}},include:taskInclude}));},
    bulkComplete:async(userId,ids,completedAt)=>{await ensureTaskIds(userId,ids);await prisma.task.updateMany({where:{id:{in:ids},userId,deletedAt:null},data:{status:"COMPLETED",completedAt,revision:{increment:1}}});return(await prisma.task.findMany({where:{id:{in:ids},userId},include:taskInclude})).map(serializeTask);},
    bulkDelete:async(userId,ids)=>{await ensureTaskIds(userId,ids);await prisma.task.updateMany({where:{id:{in:ids},userId,deletedAt:null},data:{deletedAt:new Date(),revision:{increment:1}}});},
    bulkUpdate:async(userId,input)=>{await ensureTaskIds(userId,input.ids);validateRecurrence(input.recurrenceRule);await validateRelations(userId,input);const current=await prisma.task.findMany({where:{id:{in:input.ids},userId,deletedAt:null},select:{id:true,startAt:true,endAt:true,dueDate:true,dueAt:true}});const schedules=new Map(current.map((task)=>[task.id,mergedSchedule(task,input)]));await prisma.$transaction(async(tx)=>{for(const id of input.ids){const s=schedules.get(id)!;const data:Record<string,unknown>={revision:{increment:1}};if(input.title!==undefined)data.title=input.title;if(input.priority!==undefined)data.priority=priority(input.priority);if(input.startAt!==undefined)data.startAt=s.startAt?new Date(s.startAt):null;if(input.endAt!==undefined)data.endAt=s.endAt?new Date(s.endAt):null;if(input.dueDate!==undefined){data.dueDate=s.due.date?new Date(`${s.due.date}T00:00:00Z`):null;if(input.dueAt===undefined)data.dueAt=null;}if(input.dueAt!==undefined){data.dueAt=s.due.at?new Date(s.due.at):null;if(input.dueDate===undefined)data.dueDate=null;}if(input.recurrenceRule!==undefined)data.recurrenceRule=input.recurrenceRule;if(input.projectId!==undefined)data.projectId=input.projectId;await tx.task.update({where:{id},data});}if(input.addTagIds?.length){const existing=await tx.taskTag.findMany({where:{taskId:{in:input.ids},tagId:{in:input.addTagIds}}});const set=new Set(existing.map((x)=>`${x.taskId}:${x.tagId}`));const rows=input.ids.flatMap((taskId)=>input.addTagIds!.filter((tagId)=>!set.has(`${taskId}:${tagId}`)).map((tagId)=>({taskId,tagId})));if(rows.length)await tx.taskTag.createMany({data:rows,skipDuplicates:true});}if(input.removeTagIds?.length)await tx.taskTag.deleteMany({where:{taskId:{in:input.ids},tagId:{in:input.removeTagIds}}});});return(await prisma.task.findMany({where:{id:{in:input.ids},userId},include:taskInclude})).map(serializeTask);},
    search:async(userId,query)=>(await prisma.task.findMany({where:{userId,deletedAt:null,OR:[{title:{contains:query,mode:"insensitive"}},{description:{contains:query,mode:"insensitive"}},{location:{contains:query,mode:"insensitive"}},{project:{name:{contains:query,mode:"insensitive"},deletedAt:null}},{tags:{some:{tag:{userId,deletedAt:null,name:{contains:query,mode:"insensitive"}}}}},{comments:{some:{deletedAt:null,body:{contains:query,mode:"insensitive"}}}}]},include:taskInclude,orderBy:[{sortOrder:"asc"},{createdAt:"desc"}]})).map(serializeTask),
    captureSnapshot:snapshot,restoreSnapshot,
  },
  views:{
    inbox:async(userId,includeCompleted=false)=>(await prisma.task.findMany({where:{userId,deletedAt:null,status:includeCompleted?{in:["OPEN","COMPLETED"]}:"OPEN",projectId:null},include:taskInclude,orderBy:[{sortOrder:"asc"},{createdAt:"desc"}]})).map(serializeTask),
    today:async(userId,now,tz,includeCompleted=false)=>{const b=dayBoundsInTimezone(now,tz),d=new Date(`${b.date}T00:00:00Z`),n=new Date(`${b.nextDate}T00:00:00Z`);return(await prisma.task.findMany({where:{userId,deletedAt:null,status:includeCompleted?{in:["OPEN","COMPLETED"]}:"OPEN",OR:[{startAt:{gte:b.start,lte:b.end}},{startAt:null,dueAt:{gte:b.start,lte:b.end}},{startAt:null,dueAt:null,dueDate:{gte:d,lt:n}}]},include:taskInclude,orderBy:[{startAt:"asc"},{dueDate:"asc"},{dueAt:"asc"},{sortOrder:"asc"}]})).map(serializeTask);},
    upcoming:async(userId,now,tz,includeCompleted=false)=>{const b=dayBoundsInTimezone(now,tz),n=new Date(`${b.nextDate}T00:00:00Z`);return(await prisma.task.findMany({where:{userId,deletedAt:null,status:includeCompleted?{in:["OPEN","COMPLETED"]}:"OPEN",OR:[{startAt:{gt:b.end}},{startAt:null,dueAt:{gt:b.end}},{startAt:null,dueAt:null,dueDate:{gte:n}}]},include:taskInclude,orderBy:[{startAt:"asc"},{dueDate:"asc"},{dueAt:"asc"},{sortOrder:"asc"}]})).map(serializeTask);},
    overdue:async(userId,now,tz)=>{const date=formatDateInTimezone(now,tz),d=new Date(`${date}T00:00:00Z`);return(await prisma.task.findMany({where:{userId,deletedAt:null,status:"OPEN",OR:[{dueDate:{lt:d}},{dueAt:{lt:now}}]},include:taskInclude,orderBy:[{dueDate:"asc"},{dueAt:"asc"}]})).map(serializeTask);},
    completed:async(userId)=>(await prisma.task.findMany({where:{userId,deletedAt:null,status:"COMPLETED"},include:taskInclude,orderBy:{completedAt:"desc"}})).map(serializeTask),
    focus:async(userId,now,tz)=>{const b=dayBoundsInTimezone(now,tz),n=new Date(`${b.nextDate}T00:00:00Z`);return(await prisma.task.findMany({where:{userId,deletedAt:null,status:"OPEN",OR:[{priority:{in:["HIGH","URGENT"]}},{dueDate:{lt:n}},{dueAt:{lte:b.end}}]},include:taskInclude,orderBy:[{priority:"desc"},{dueDate:"asc"},{dueAt:"asc"},{sortOrder:"asc"}]})).map(serializeTask);},
  },
  projects:{
    list:async(userId)=>(await prisma.project.findMany({where:{userId,deletedAt:null,status:{not:"ARCHIVED"}},orderBy:{sortOrder:"asc"}})).map(serializeProject),
    create:async(userId,input)=>serializeProject(await prisma.project.create({data:{userId,name:input.name,description:input.description??null,color:input.color??null,icon:input.icon??null}})),
    get:async(userId,id)=>serializeProject(await ensureProject(userId,id)),
    update:async(userId,id,input)=>{await ensureProject(userId,id);const data:Record<string,unknown>={};if(input.name!==undefined)data.name=input.name;if(input.description!==undefined)data.description=input.description;if(input.color!==undefined)data.color=input.color;if(input.icon!==undefined)data.icon=input.icon;if(input.status!==undefined)data.status=input.status.toUpperCase();return serializeProject(await prisma.project.update({where:{id},data}));},
    archive:async(userId,id)=>{await ensureProject(userId,id);return serializeProject(await prisma.project.update({where:{id},data:{status:"ARCHIVED",archivedAt:new Date()}}));},
    delete:async(userId,id)=>{await ensureProject(userId,id);await prisma.project.update({where:{id},data:{deletedAt:new Date()}});},
  },
  tags:{
    list:async(userId)=>(await prisma.tag.findMany({where:{userId,deletedAt:null},orderBy:{name:"asc"}})).map(serializeTag),
    create:async(userId,input)=>{try{return serializeTag(await prisma.tag.create({data:{userId,name:input.name,color:input.color??null}}));}catch(e){if(e instanceof Error&&e.message.includes("Unique constraint"))throw Errors.Conflict(`Label "${input.name}" already exists.`);throw e;}},
    update:async(userId,id,input)=>{await ensureTags(userId,[id]);return serializeTag(await prisma.tag.update({where:{id},data:{name:input.name,color:input.color}}));},
    delete:async(userId,id)=>{await ensureTags(userId,[id]);await prisma.$transaction([prisma.taskTag.deleteMany({where:{tagId:id,task:{userId}}}),prisma.tag.update({where:{id},data:{deletedAt:new Date()}})]);},
    getByName:async(userId,name)=>{const t=await prisma.tag.findFirst({where:{userId,name,deletedAt:null}});return t?serializeTag(t):null;},verifyBelongToUser:ensureTags,
  },
  comments:{
    list:async(userId,taskId)=>{await ensureTask(userId,taskId);return(await prisma.comment.findMany({where:{taskId,userId,deletedAt:null},orderBy:{createdAt:"asc"}})).map(serializeComment);},
    create:async(userId,taskId,input)=>{await ensureTask(userId,taskId);return serializeComment(await prisma.comment.create({data:{userId,taskId,body:input.body}}));},
    update:async(userId,taskId,id,input)=>{await ensureTask(userId,taskId);const c=await prisma.comment.findFirst({where:{id,taskId,userId,deletedAt:null}});found(c,"Comment");return serializeComment(await prisma.comment.update({where:{id},data:{body:input.body}}));},
    delete:async(userId,taskId,id)=>{await ensureTask(userId,taskId);const c=await prisma.comment.findFirst({where:{id,taskId,userId,deletedAt:null}});found(c,"Comment");await prisma.comment.update({where:{id},data:{deletedAt:new Date()}});},
  },
  reminders:{
    list:async(userId,taskId)=>{await ensureTask(userId,taskId);return(await prisma.reminder.findMany({where:{userId,taskId,deletedAt:null},orderBy:{remindAt:"asc"}})).map(serializeReminder);},
    create:async(userId,taskId,input)=>{await ensureTask(userId,taskId);return serializeReminder(await prisma.reminder.create({data:{userId,taskId,remindAt:new Date(input.remindAt),channel:input.channel??"hermes_telegram"}}));},
    update:async(userId,id,input)=>{const r=await prisma.reminder.findFirst({where:{id,userId,deletedAt:null}});found(r,"Reminder");return serializeReminder(await prisma.reminder.update({where:{id},data:{remindAt:input.remindAt?new Date(input.remindAt):undefined,channel:input.channel,status:input.status}}));},
    delete:async(userId,id)=>{const r=await prisma.reminder.findFirst({where:{id,userId,deletedAt:null}});found(r,"Reminder");await prisma.reminder.update({where:{id},data:{deletedAt:new Date()}});},
  },
  events:{
    list:async(userId,taskId)=>{if(taskId)await ensureTask(userId,taskId,true);return(await prisma.taskEvent.findMany({where:{userId,taskId:taskId??undefined},orderBy:{createdAt:"desc"},take:100})).map(serializeTaskEvent);},
    record:async(userId,taskId,kind,payload)=>{await ensureTask(userId,taskId,true);return serializeTaskEvent(await prisma.taskEvent.create({data:{userId,taskId,kind,payload:(payload??null) as never}}));},
  },
  operations:{
    record:async(userId,kind,payload,taskId)=>serializeOperation(await prisma.operation.create({data:{userId,kind:kind as never,payload:payload as never,taskId}})),
    list:async(userId)=>(await prisma.operation.findMany({where:{userId},orderBy:[{createdAt:"desc"},{id:"desc"}],take:3})).map(serializeOperation),
    undoLast:async(userId)=>{const o=await prisma.operation.findFirst({where:{userId,undoneAt:null},orderBy:[{createdAt:"desc"},{id:"desc"}]});found(o,"Operation");return prismaRepository.operations.undo(userId,o.id);},
    undo:async(userId,id)=>{const o=await prisma.operation.findFirst({where:{id,userId}});found(o,"Operation");if(o.undoneAt)throw Errors.Conflict("Operation already undone.");const p=o.payload as Record<string,unknown>;if(o.kind==="TASK_CREATE"){const taskId=p.taskId as string;const redoSnapshots=[await snapshot(userId,taskId)];await prisma.task.update({where:{id:taskId},data:{deletedAt:new Date(),revision:{increment:1}}});return serializeOperation(await prisma.operation.update({where:{id},data:{payload:{...p,redoSnapshots} as never,undoneAt:new Date()}}));}let originals:TaskSnapshot[]=[];let spawned:string[]=[];if(o.kind==="TASK_COMPLETE"){originals=[(p.snapshot as TaskSnapshot)??(p as unknown as TaskSnapshot)];spawned=(p.spawnedTaskIds as string[])??[];}else if(["TASK_UPDATE","TASK_DELETE","TASK_REOPEN"].includes(o.kind)){originals=[(p.snapshot as TaskSnapshot)??(p as unknown as TaskSnapshot)];}else if(["TASK_BULK_UPDATE","TASK_BULK_COMPLETE","TASK_BULK_DELETE","TASK_BULK_MOVE"].includes(o.kind)){originals=(p.snapshots as TaskSnapshot[])??[];spawned=(p.spawnedTaskIds as string[])??[];}else throw Errors.Validation(`Undo not supported for operation kind: ${o.kind}`);const redoSnapshots=await Promise.all([...originals.map((s)=>s.taskId),...spawned].map((taskId)=>snapshot(userId,taskId)));for(const s of originals)await restoreSnapshot(userId,s);if(spawned.length)await prisma.task.updateMany({where:{id:{in:spawned},userId},data:{deletedAt:new Date(),revision:{increment:1}}});return serializeOperation(await prisma.operation.update({where:{id},data:{payload:{...p,redoSnapshots} as never,undoneAt:new Date()}}));},
    redoLast:async(userId)=>{const o=await prisma.operation.findFirst({where:{userId,undoneAt:{not:null}},orderBy:[{undoneAt:"desc"},{createdAt:"asc"},{id:"asc"}]});found(o,"Operation");return prismaRepository.operations.redo(userId,o.id);},
    redo:async(userId,id)=>{const o=await prisma.operation.findFirst({where:{id,userId}});found(o,"Operation");if(!o.undoneAt)throw Errors.Conflict("Operation is not undone.");const p=o.payload as Record<string,unknown>;const redo=(p.redoSnapshots as TaskSnapshot[])??[];if(!redo.length)throw Errors.Conflict("Operation cannot be redone.");for(const s of redo)await restoreSnapshot(userId,s);return serializeOperation(await prisma.operation.update({where:{id},data:{undoneAt:null}}));},
  },
};
